name: Check PR title format

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: actions/github-script@v7
        with:
          script: |
            const title = github.context.payload.pull_request.title;
            // Matches: [KBS-123] : Some title
            const pattern = /^\[KBS-\d+\] ?: .+/;

            if (!pattern.test(title)) {
              core.setFailed(`❌ Invalid PR title: "${title}".
              The title must follow the pattern "[KBS-<number>] : <description>", e.g. "[KBS-12] : Fix bug in login form".`);
            } else {
              console.log(`✅ PR title "${title}" matches the required format.`);
            }
