#DO NOT CHANGE
name: Deploy Frontend to Production

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # This job MUST run on your self-hosted runner
    runs-on: self-hosted

    steps:
      - name: 'Pull Latest Code & Rebuild Frontend Container'
        run: |
          echo "Starting Frontend deployment..."
          # Go into the Frontend's specific source code directory on the VM
          cd /opt/booking_system/frontend
          
          # Pull the latest changes from the main branch
          git pull

          # Go back to the main project directory to access the docker-compose file
          cd /opt/booking_system

          # Rebuild and restart ONLY the frontend service
          docker-compose up -d --build frontend
          
          echo "Frontend deployment successful!"